#!/bin/sh
#
# Run all dotfiles installers.

cd "$(dirname "$0")"/.. || exit 1

# find the installers and run them iteratively
# Note: </dev/null prevents installers from consuming the pipeline's stdin
git ls-tree --name-only -r HEAD | grep install.sh | while read -r installer; do
	echo "› ${installer}..."
	sh -c "$installer" </dev/null
done